### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/root/sda2/WSQ/HEAL/data/OPV2V/train/2021_09_10_12_07_11/216/000309_depth0.png'

### ISSUE THREAD

**Issue by Lesliewsq** [yifanlu0227/HEAL#6]
`python opencood/tools/train.py -y opencood/hypes_yaml/opv2v/MoreModality/2_modality_end2end_training/lidar_camera_coalign.yaml`

**Comment by yifanlu0227** [comment]
Hi, you need to download the OPV2V-H dataset, which includes the depth file.

**Comment by Lesliewsq** [comment]
I have downloaded the original OPV2V dataset and created a dataset folder under HEAL as follow. Should I put `OPV2V-H-depth.zip ` and `OPV2V-H-LiDAR.zip`  under /HEAL/OPV2V/ and then unzip them or just put them under a new folder and then unzip them?

├── OPV2V
│   ├── additional
│   ├── test
│   ├── train
│   └── validate

**Comment by yifanlu0227** [comment]
Please unzip the `OPV2V-H-depth.zip` and `OPV2V-H-LiDAR.zip` outside of `OPV2V` folder. They will produce a parallel folder `OPV2V-H`, just as the README illustrated.

**Comment by Lesliewsq** [comment]
Still the same error.  
![1710411995805](https://github.com/yifanlu0227/HEAL/assets/81459252/ac7aa4e4-c014-44cc-ae11-bd0b08c5b7d4)
![1710411947087](https://github.com/yifanlu0227/HEAL/assets/81459252/78822155-71cf-44b7-bbeb-810baa88fb04)

**Comment by xhjy2020** [comment]
> Still the same error. ![1710411995805](https://private-user-images.githubusercontent.com/81459252/312799760-ac7aa4e4-c014-44cc-ae11-bd0b08c5b7d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTQ0NDUsIm5iZiI6MTcxMDQxNDE0NSwicGF0aCI6Ii84MTQ1OTI1Mi8zMTI3OTk3NjAtYWM3YWE0ZTQtYzAxNC00NGNjLWFlMTEtYmQwYjA4YzViN2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDExMDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTkwOTFlNWE2Y2VhMmY3Mjc2NjZmMmViNzYxMWEwNjYxZjE3MDk3OGMxMmExMTExZTM0N2M4YmVhZTM5OGQzYTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.FjaLD5luFpBzaVD6FOhvvapDqudBNumWkSe0XVCUbrI) ![1710411947087](https://private-user-images.githubusercontent.com/81459252/312799771-78822155-71cf-44b7-bbeb-810baa88fb04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTQ0NDUsIm5iZiI6MTcxMDQxNDE0NSwicGF0aCI6Ii84MTQ1OTI1Mi8zMTI3OTk3NzEtNzg4MjIxNTUtNzFjZi00NGI3LWJiZWItODEwYmFhODhmYjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDExMDIyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2MWY4ZTMzOTJhMmUxODkyNzhhNTk5ZWZhNDI3OWYxOWNlMjg3YzliYTIxZWZiZTZhNTk2NDVmYjQ4MDE0ZTMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wHHlSdhgaMaL8vSI_GEmuEMqodw4PRF_R-EwML3zb4E)

+1

**Comment by xhjy2020** [comment]
> Still the same error. ![1710411995805](https://private-user-images.githubusercontent.com/81459252/312799760-ac7aa4e4-c014-44cc-ae11-bd0b08c5b7d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTQ1NTMsIm5iZiI6MTcxMDQxNDI1MywicGF0aCI6Ii84MTQ1OTI1Mi8zMTI3OTk3NjAtYWM3YWE0ZTQtYzAxNC00NGNjLWFlMTEtYmQwYjA4YzViN2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDExMDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMWFhMWUzOTBlMDE1M2IzYjc3NDMwOGM1YWU3ZjQ3NDZlZWU1ZDg5YmVkNjBkNzQwZTI2YTgwMmEwNWEwY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LXmB2LFoJGAP5OU79mXv6VkYvX-MRO0WrNTygBHYa_s) ![1710411947087](https://private-user-images.githubusercontent.com/81459252/312799771-78822155-71cf-44b7-bbeb-810baa88fb04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTQ1NTMsIm5iZiI6MTcxMDQxNDI1MywicGF0aCI6Ii84MTQ1OTI1Mi8zMTI3OTk3NzEtNzg4MjIxNTUtNzFjZi00NGI3LWJiZWItODEwYmFhODhmYjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDExMDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZWUzMTQzMTQwNWM4MzhjNmYyOWE4YWQ0YmI4ZWY2Y2IzNDUyNGQ3NTBkYzU5YmMwZWViOTNiN2VkMjYyMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bfi2u09boD5CgU6jkHGS7pZWNkb9AQd2BTfIX9ARbXY)

+1, It seems that the default configuration file does not point to depth data.

**Comment by Lesliewsq** [comment]
> > Still the same error. ![1710411995805](https://private-user-images.githubusercontent.com/81459252/312799760-ac7aa4e4-c014-44cc-ae11-bd0b08c5b7d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTQ1NTMsIm5iZiI6MTcxMDQxNDI1MywicGF0aCI6Ii84MTQ1OTI1Mi8zMTI3OTk3NjAtYWM3YWE0ZTQtYzAxNC00NGNjLWFlMTEtYmQwYjA4YzViN2Q0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDExMDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAzMWFhMWUzOTBlMDE1M2IzYjc3NDMwOGM1YWU3ZjQ3NDZlZWU1ZDg5YmVkNjBkNzQwZTI2YTgwMmEwNWEwY2ImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LXmB2LFoJGAP5OU79mXv6VkYvX-MRO0WrNTygBHYa_s) ![1710411947087](https://private-user-images.githubusercontent.com/81459252/312799771-78822155-71cf-44b7-bbeb-810baa88fb04.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0MTQ1NTMsIm5iZiI6MTcxMDQxNDI1MywicGF0aCI6Ii84MTQ1OTI1Mi8zMTI3OTk3NzEtNzg4MjIxNTUtNzFjZi00NGI3LWJiZWItODEwYmFhODhmYjA0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE0VDExMDQxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlZWUzMTQzMTQwNWM4MzhjNmYyOWE4YWQ0YmI4ZWY2Y2IzNDUyNGQ3NTBkYzU5YmMwZWViOTNiN2VkMjYyMGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bfi2u09boD5CgU6jkHGS7pZWNkb9AQd2BTfIX9ARbXY)
> 
> +1, It seems that the default configuration file does not point to depth data.
Yeah，I found that the camera.png and depth.png data are read from the same path, but aren't they placed in two different datasets?

**Comment by yifanlu0227** [comment]
I'm very sorry about that. @xhjy2020 @Lesliewsq 
Please modify line 150 in `opencood/data_utils/datasets/basedataset/opv2v_basedataset.py` to

```
                    depth_files = self.find_camera_files(cav_path, 
                                                timestamp, sensor="depth").replace("OPV2V", "OPV2V-H")
```


There are other fixes for OPV2V-H dataset file reading. Please use the latest commit via
```
git fetch origin
git merge origin/main
```

**Comment by yifanlu0227** [comment]
This is because I convert the RGB image & depth image into a hdf5 file for fast loading. In this case, I do not load the depth image from `OPV2V_Hetero` folder and omit the error. Please note that it's `OPV2V_Hetero` not `OPV2V-H`

**Comment by yifanlu0227** [comment]
By the way, you can also speed up the image loading by storing all images in an HDF5 format. They are larger but facilitate your training speed. 

You can find the convertion script in `opencood/utils/img2hdf5.py`

**Comment by xhjy2020** [comment]
> By the way, you can also speed up the image loading by storing all images in an HDF5 format. They are larger but facilitate your training speed.
> 
> You can find the conversion script in `opencood/utils/img2hdf5.py`

Nice! thank you very much for your patient explanation!!

**Comment by yifanlu0227** [comment]
I hope I didn't cause more trouble. 

I just pushed the third commit and apologize for my typo again @xhjy2020 

```
                    depth_files = self.find_camera_files(cav_path, 
                                                timestamp, sensor="depth")
                    depth_files = [depth_file.replace("OPV2V", "OPV2V_Hetero") for depth_file in depth_files]
```

**Comment by Lesliewsq** [comment]
I have tried this command  `python opencood/tools/train.py -y opencood/hypes_yaml/opv2v/MoreModality/2_modality_end2end_training/lidar_camera_coalign.yaml`  , and an error occurred. However，`opencood/hypes_yaml/opv2v/MoreModality/2_modality_end2end_training/lidar_camera_attfuse.yaml`  works.

It seems `lidar_camera_coalign.yaml` config file has problem with it.
> 
> No model_train_init function
> Traceback (most recent call last):
>   File "opencood/tools/train.py", line 189, in <module>
>     main()
>   File "opencood/tools/train.py", line 118, in main
>     ouput_dict = model(batch_data['ego'])
>   File "/root/miniconda3/envs/CoAlign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/sda2/WSQ/HEAL/opencood/models/heter_model_baseline_ms.py", line 212, in forward
>     cls_preds = self.cls_head(fused_feature)
>   File "/root/miniconda3/envs/CoAlign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/CoAlign/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 446, in forward
>     return self._conv_forward(input, self.weight, self.bias)
>   File "/root/miniconda3/envs/CoAlign/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 443, in _conv_forward
>     self.padding, self.dilation, self.groups)
> RuntimeError: Given groups=1, weight of size [2, 256, 1, 1], expected input[1, 384, 256, 256] to have 256 channels, but got 384 channels instead.

**Comment by yifanlu0227** [comment]
Yes, the `shrink_header` is missing. Please check the latest commit and now it should work. @Lesliewsq

**Comment by Lesliewsq** [comment]
Thanks for the reply. Nice work！

**Comment by Lesliewsq** [comment]
Thanks for the reply. Nice work！ @yifanlu0227

**Comment by Lesliewsq** [comment]
Both 3_modality and 4_modality yaml files report "channel size mismatch" error.
`CUDA_VISIBLE_DEVICES=1 python opencood/tools/train.py -y opencood/hypes_yaml/opv2v/MoreModality/3_modality_end2end_training/m1m2m3_pyramid.yaml `
> Traceback (most recent call last):
>   File "opencood/tools/train.py", line 189, in <module>
>     main()
>   File "opencood/tools/train.py", line 118, in main
>     ouput_dict = model(batch_data['ego'])
>   File "/root/miniconda3/envs/CoAlign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/sda2/WSQ/HEAL/opencood/models/heter_pyramid_collab.py", line 145, in forward
>     feature = eval(f"self.encoder_{modality_name}")(data_dict, modality_name)
>   File "/root/miniconda3/envs/CoAlign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/sda2/WSQ/HEAL/opencood/models/heter_encoders.py", line 79, in forward
>     batch_dict = self.spconv_block(batch_dict)
>   File "/root/miniconda3/envs/CoAlign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/sda2/WSQ/HEAL/opencood/models/sub_modules/sparse_backbone_3d.py", line 114, in forward
>     x = self.conv_input(input_sp_tensor)
>   File "/root/miniconda3/envs/CoAlign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/CoAlign/lib/python3.7/site-packages/spconv/pytorch/modules.py", line 137, in forward
>     input = module(input)
>   File "/root/miniconda3/envs/CoAlign/lib/python3.7/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
>     return forward_call(*input, **kwargs)
>   File "/root/miniconda3/envs/CoAlign/lib/python3.7/site-packages/spconv/pytorch/conv.py", line 187, in forward
>     1] == self.in_channels, "channel size mismatch"
> AssertionError: channel size mismatch

**Comment by xhjy2020** [comment]
same error when i train m3_no_fusion using `opencood/hypes_yaml/opv2v/Single/m3_SECOND32_pretrain.yaml`.
![image](https://github.com/yifanlu0227/HEAL/assets/65607895/85980a28-25f9-4539-bd1b-1278731913d4)

**Comment by yifanlu0227** [comment]
Are you using spconv 2.x?

**Comment by xhjy2020** [comment]
> Are you using spconv 2.x? Could you provide more error information?

yes, the version is spconv-cu117, 2.3.6
![image](https://github.com/yifanlu0227/HEAL/assets/65607895/d5ffdb08-9556-49b1-8d2f-6c080327b3d7)

**Comment by xhjy2020** [comment]
> > Are you using spconv 2.x? Could you provide more error information?
> 
> yes, the version is spconv-cu117, 2.3.6 ![image](https://private-user-images.githubusercontent.com/65607895/322488679-d5ffdb08-9556-49b1-8d2f-6c080327b3d7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0MzkyODYsIm5iZiI6MTcxMzQzODk4NiwicGF0aCI6Ii82NTYwNzg5NS8zMjI0ODg2NzktZDVmZmRiMDgtOTU1Ni00OWIxLThkMmYtNmMwODAzMjdiM2Q3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE4VDExMTYyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTMzMzJiOGU2ODllYjliNzVmNzAwNTZmNTg1N2E3YTg1NzllYjY0ZWNiOTY3Y2YxMjUwN2YyZTViMDRjODNmMzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.nCvtjWw2eSp_majHz-uOyUOIYUFIzOUV4yyMrAqI_DQ)

It is indeed an issue with the spconv version. I replaced 2.3.6 with 1.2.1, then this issue won't occur anymore. Thanks!!
